name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-swift-latest:
    name: Library (swift-latest)
    runs-on: macos-13
    strategy:
      matrix:
        config: ['debug', 'release']
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Run ${{ matrix.config }} tests
        run: CONFIG=${{ matrix.config }} make test-library
      - name: Build platforms ${{ matrix.config }}
        run: CONFIG=${{ matrix.config }} make build-all-platforms
        
  library-evolution:
    name: Library (evolution)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Build for library evolution
        run: make build-for-library-evolution
          
  library-swift-5-7:
    name: Library (swift 5.7)
    runs-on: macos-12
    strategy:
      matrix:
        config: ['debug', 'release']
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.2
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Run ${{ matrix.config }} tests
        run: CONFIG=${{ matrix.config }} make test-library
      - name: Build platforms ${{ matrix.config }}
        run: CONFIG=${{ matrix.config }} make build-all-platforms
        
  ubuntu-tests:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test-swift

  static-stdlib:
    strategy:
      matrix:
        image: ['swift:5.7-focal', 'swift:5.8-focal']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v3
      - name: Build for static-stdlib (debug)
        run: swift build -c debug --static-swift-stdlib
      - name: Build for static-stdlib (release)
        run: swift build -c release --static-swift-stdlib
